# Generated by Django 2.2.5 on 2022-04-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='is_sevice_provider',
            new_name='is_service_provider',
        ),
    ]
