# Generated by Django 4.0.3 on 2022-04-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220404_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
