# Generated by Django 4.0.3 on 2022-04-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220426_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
