# Generated by Django 4.0.3 on 2022-05-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20220509_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
