# Generated by Django 2.2.5 on 2022-06-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_mydata_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
