# Generated by Django 2.2.5 on 2022-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.IntegerField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('female', models.BooleanField(default=False)),
                ('male', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('lv', 'Love'), ('ht', 'Hate')], max_length=200)),
            ],
        ),
    ]
