# Generated by Django 4.0.3 on 2022-04-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_create_service_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
