# Generated by Django 2.2.5 on 2022-05-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_create_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_service',
            name='category',
            field=models.CharField(choices=[('lv', 'Love'), ('ht', 'Hate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='create_service',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='create_service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='create_service',
            name='service_name',
            field=models.CharField(max_length=100),
        ),
    ]
