# Generated by Django 4.0.3 on 2022-05-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220509_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_service',
            name='category',
            field=models.CharField(choices=[('Love', 'Lv'), ('Hate', 'Ht')], max_length=100),
        ),
        migrations.AlterField(
            model_name='create_service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='create_service',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
