# Generated by Django 4.0.3 on 2022-05-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_create_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_service',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='create_service',
            name='category',
            field=models.CharField(choices=[('LV', 'LOVE'), ('HV', 'HATE')], max_length=100),
        ),
    ]
