# Generated by Django 2.2.5 on 2022-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220603_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_service',
            name='category',
            field=models.CharField(choices=[('Salon', 'Salon'), ('Carpentry', 'Carpentry'), ('Tailoring', 'Tailoring'), ('Construction Work', 'Construction Work')], max_length=100),
        ),
    ]
