# Generated by Django 4.0.3 on 2022-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220607_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_service',
            name='category',
            field=models.CharField(choices=[('Salon', 'Salon'), ('Carpentry', 'Carpentry'), ('Tailoring', 'Tailoring'), ('Construction Work', 'Construction Work'), ('House Keeping', 'House Keeping')], max_length=100),
        ),
        migrations.AlterField(
            model_name='create_service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
