# Generated by Django 4.0.3 on 2022-06-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_create_service_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_service',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('service_requested_name', models.CharField(max_length=100)),
                ('day_for_the_service', models.DateField()),
                ('date_service_was_requested', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
