# Generated by Django 4.0.3 on 2022-06-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_request_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_service',
            old_name='service_requested_name',
            new_name='name_of_service_requested',
        ),
        migrations.AlterField(
            model_name='request_service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
